### PR TITLE
logout route

### LINKED ISSUE #26: POST/ logout route
#### logout  Route
 delete cookies and token

#### Route :
 `
api/v1/logout
`
--

#### Method : POST 
---
#### Response : 
Response may be success or error :
* Error :
```javascript
      {
        status:400,
        message: "logging out failed"'
    }
```
* Success
```javascript
    {
        status:200,
        message: "logged out successfully"
    }
```

### PR DESCRIPTION
**Pull request by khamis-hesham**
fix #26 

- [x] add logout route.
- [x] made test for logout route.

### CODE REVIEW

File: server/routes/index.js [hunk 1]
```diff
@@ -2,8 +2,8 @@ const express = require('express');
...
 const router = express.Router();
 
-router.get('/hi', (req, res) => {
-  res.send('hi');
-});
+const { logOut } = require('../controller');
+
+router.post('/logout', logOut);
 
 module.exports = router;
```
Comment (mFlaifel) [inline server/routes/index.js:9]: please see [this](https://github.com/GSG-G9/beauty-salon/pull/53#discussion_r603544687)

Comment (mFlaifel) [inline server/routes/index.js:9]: please see [this](https://github.com/GSG-G9/beauty-salon/pull/53#discussion_r603544687)
